# Generated by Django 3.1.3 on 2021-02-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarenKategorien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Waren_Kategorien_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WarenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ware_Name', models.CharField(max_length=150)),
                ('Ware_Preis', models.FloatField(default=0)),
                ('Ware_Info', models.CharField(max_length=8000)),
                ('Ware_Bild', models.ImageField(upload_to='Waren')),
                ('Ware_Kategorien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Waren.warenkategorien')),
            ],
        ),
    ]
